export const FETCH_LOGIN_USER = "FETCH_LOGIN_USER";
export const FETCH_LOGIN_USER_SUCCESS = "FETCH_LOGIN_USER_SUCCESS";
export const FETCH_LOGIN_USER_ERROR = "FETCH_LOGIN_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";

export const FETCH_REGISTER_USER = "FETCH_REGISTER_USER";
export const FETCH_REGISTER_USER_SUCCESS = "FETCH_REGISTER_USER_SUCCESS";
export const FETCH_REGISTER_USER_ERROR = "FETCH_REGISTER_USER_ERROR";
