export const ADD_HOTEL = "ADD_HOTEL";

export const FETCH_HOTELS_REQUEST = "FETCH_HOTELS";
export const FETCH_HOTELS_SUCCESS = "FETCH_HOTELS_SUCCESS";
export const FETCH_HOTELS_ERROR = "FETCH_HOTELS_ERROR";

export const FETCH_HOTEL_DETAILS = "FETCH_HOTEL_DETAILS";
export const FETCH_HOTEL_DETAILS_SUCCESS = "FETCH_HOTEL_DETAILS_SUCCESS";
export const FETCH_HOTEL_DETAILS_ERROR = "FETCH_HOTEL_DETAILS_ERROR";

export const TOGGLE_FAVOURITES_REQUEST = "TOGGLE_FAVOURITES_REQUEST";
export const TOGGLE_FAVOURITES_SUCCESS = "TOGGLE_FAVOURITES_SUCCESS";
export const TOGGLE_FAVOURITES_ERROR = "TOGGLE_FAVOURITES_ERROR";

export const FETCH_FAV_HOTELS_REQUEST = "FETCH_FAV_HOTELS_REQUEST";
export const FETCH_FAV_HOTELS_SUCCESS = "FETCH_FAV_HOTELS_SUCCESS";
export const FETCH_FAV_HOTELS_ERROR = "FETCH_FAV_HOTELS_ERROR";

export const ADD_REMOVE_FAV_HOTEL = "ADD_REMOVE_FAV_HOTEL";

export const RESET_HOTEL_STATE = "RESET_HOTEL_STATE";
