export const ADD_HOTEL = "ADD_HOTEL";

export const FETCH_HOTELS_REQUEST = "FETCH_HOTELS";
export const FETCH_HOTELS_SUCCESS = "FETCH_HOTELS_SUCCESS";
export const FETCH_HOTELS_ERROR = "FETCH_HOTELS_ERROR";

export const FETCH_HOTEL_DETAILS = "FETCH_HOTEL_DETAILS";
export const FETCH_HOTEL_DETAILS_SUCCESS = "FETCH_HOTEL_DETAILS_SUCCESS";
export const FETCH_HOTEL_DETAILS_ERROR = "FETCH_HOTEL_DETAILS_ERROR";
